//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JuicySwapper.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.6.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Program Files\\Epic Games\\Fortnite\\FortniteGame\\Content\\Paks")]
        public string pakPath {
            get {
                return ((string)(this["pakPath"]));
            }
            set {
                this["pakPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool openfortnite {
            get {
                return ((bool)(this["openfortnite"]));
            }
            set {
                this["openfortnite"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int offsetskin1 {
            get {
                return ((int)(this["offsetskin1"]));
            }
            set {
                this["offsetskin1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int offsetpick {
            get {
                return ((int)(this["offsetpick"]));
            }
            set {
                this["offsetpick"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int offsetback {
            get {
                return ((int)(this["offsetback"]));
            }
            set {
                this["offsetback"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int offsetskin2 {
            get {
                return ((int)(this["offsetskin2"]));
            }
            set {
                this["offsetskin2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int offsetemote {
            get {
                return ((int)(this["offsetemote"]));
            }
            set {
                this["offsetemote"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int offsetlobby {
            get {
                return ((int)(this["offsetlobby"]));
            }
            set {
                this["offsetlobby"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int offsetpickmesh {
            get {
                return ((int)(this["offsetpickmesh"]));
            }
            set {
                this["offsetpickmesh"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public long current_offset {
            get {
                return ((long)(this["current_offset"]));
            }
            set {
                this["current_offset"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool RenegadeEnabled {
            get {
                return ((bool)(this["RenegadeEnabled"]));
            }
            set {
                this["RenegadeEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool GhoulOGEnabled {
            get {
                return ((bool)(this["GhoulOGEnabled"]));
            }
            set {
                this["GhoulOGEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool RedNosedEnabled {
            get {
                return ((bool)(this["RedNosedEnabled"]));
            }
            set {
                this["RedNosedEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool opendiscord {
            get {
                return ((bool)(this["opendiscord"]));
            }
            set {
                this["opendiscord"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool BKEnabled {
            get {
                return ((bool)(this["BKEnabled"]));
            }
            set {
                this["BKEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool StealthReflexEnabled {
            get {
                return ((bool)(this["StealthReflexEnabled"]));
            }
            set {
                this["StealthReflexEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SparkplugEnabled {
            get {
                return ((bool)(this["SparkplugEnabled"]));
            }
            set {
                this["SparkplugEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool WonderEnabled {
            get {
                return ((bool)(this["WonderEnabled"]));
            }
            set {
                this["WonderEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int defaulthead {
            get {
                return ((int)(this["defaulthead"]));
            }
            set {
                this["defaulthead"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int defaultbody {
            get {
                return ((int)(this["defaultbody"]));
            }
            set {
                this["defaultbody"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AerialEnabled {
            get {
                return ((bool)(this["AerialEnabled"]));
            }
            set {
                this["AerialEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool RubyEnabled {
            get {
                return ((bool)(this["RubyEnabled"]));
            }
            set {
                this["RubyEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool BracerEnabled {
            get {
                return ((bool)(this["BracerEnabled"]));
            }
            set {
                this["BracerEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SkullRangerEnabled {
            get {
                return ((bool)(this["SkullRangerEnabled"]));
            }
            set {
                this["SkullRangerEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool PunchyEnabled {
            get {
                return ((bool)(this["PunchyEnabled"]));
            }
            set {
                this["PunchyEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AutumnQueenEnabled {
            get {
                return ((bool)(this["AutumnQueenEnabled"]));
            }
            set {
                this["AutumnQueenEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool BoltEnabled {
            get {
                return ((bool)(this["BoltEnabled"]));
            }
            set {
                this["BoltEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool BirdieEnabled {
            get {
                return ((bool)(this["BirdieEnabled"]));
            }
            set {
                this["BirdieEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DoublecrossEnabled {
            get {
                return ((bool)(this["DoublecrossEnabled"]));
            }
            set {
                this["DoublecrossEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool HushEnabled {
            get {
                return ((bool)(this["HushEnabled"]));
            }
            set {
                this["HushEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool HeidiEnabled {
            get {
                return ((bool)(this["HeidiEnabled"]));
            }
            set {
                this["HeidiEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SparkleEnabled {
            get {
                return ((bool)(this["SparkleEnabled"]));
            }
            set {
                this["SparkleEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool GlowEnabled {
            get {
                return ((bool)(this["GlowEnabled"]));
            }
            set {
                this["GlowEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IkonikEnabled {
            get {
                return ((bool)(this["IkonikEnabled"]));
            }
            set {
                this["IkonikEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MezmerEnabled {
            get {
                return ((bool)(this["MezmerEnabled"]));
            }
            set {
                this["MezmerEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ZadieEnabled {
            get {
                return ((bool)(this["ZadieEnabled"]));
            }
            set {
                this["ZadieEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool RenegadeCEnabled {
            get {
                return ((bool)(this["RenegadeCEnabled"]));
            }
            set {
                this["RenegadeCEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ScarletEnabled {
            get {
                return ((bool)(this["ScarletEnabled"]));
            }
            set {
                this["ScarletEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool InfernoEnabled {
            get {
                return ((bool)(this["InfernoEnabled"]));
            }
            set {
                this["InfernoEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool WorldWarriorEnabled {
            get {
                return ((bool)(this["WorldWarriorEnabled"]));
            }
            set {
                this["WorldWarriorEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShadowbirdEnabled {
            get {
                return ((bool)(this["ShadowbirdEnabled"]));
            }
            set {
                this["ShadowbirdEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool FinesseEnabled {
            get {
                return ((bool)(this["FinesseEnabled"]));
            }
            set {
                this["FinesseEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool PoisedEnabled {
            get {
                return ((bool)(this["PoisedEnabled"]));
            }
            set {
                this["PoisedEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ClashEnabled {
            get {
                return ((bool)(this["ClashEnabled"]));
            }
            set {
                this["ClashEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool BriteBomberEnabled {
            get {
                return ((bool)(this["BriteBomberEnabled"]));
            }
            set {
                this["BriteBomberEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool BunnyBrawlerEnabled {
            get {
                return ((bool)(this["BunnyBrawlerEnabled"]));
            }
            set {
                this["BunnyBrawlerEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ManicEnabled {
            get {
                return ((bool)(this["ManicEnabled"]));
            }
            set {
                this["ManicEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool EliteAgentEnabled {
            get {
                return ((bool)(this["EliteAgentEnabled"]));
            }
            set {
                this["EliteAgentEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DarkVoyagerEnabled {
            get {
                return ((bool)(this["DarkVoyagerEnabled"]));
            }
            set {
                this["DarkVoyagerEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TriceraOpsEnabled {
            get {
                return ((bool)(this["TriceraOpsEnabled"]));
            }
            set {
                this["TriceraOpsEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CrusherEnabled {
            get {
                return ((bool)(this["CrusherEnabled"]));
            }
            set {
                this["CrusherEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DominoEnabled {
            get {
                return ((bool)(this["DominoEnabled"]));
            }
            set {
                this["DominoEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MogulUSAEnabled {
            get {
                return ((bool)(this["MogulUSAEnabled"]));
            }
            set {
                this["MogulUSAEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MogulCANEnabled {
            get {
                return ((bool)(this["MogulCANEnabled"]));
            }
            set {
                this["MogulCANEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MogulCHNEnabled {
            get {
                return ((bool)(this["MogulCHNEnabled"]));
            }
            set {
                this["MogulCHNEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MogulFRAEnabled {
            get {
                return ((bool)(this["MogulFRAEnabled"]));
            }
            set {
                this["MogulFRAEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MogulGBREnabled {
            get {
                return ((bool)(this["MogulGBREnabled"]));
            }
            set {
                this["MogulGBREnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MogulGEREnabled {
            get {
                return ((bool)(this["MogulGEREnabled"]));
            }
            set {
                this["MogulGEREnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MogulKOREnabled {
            get {
                return ((bool)(this["MogulKOREnabled"]));
            }
            set {
                this["MogulKOREnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MogulEnabled {
            get {
                return ((bool)(this["MogulEnabled"]));
            }
            set {
                this["MogulEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ACDCEnabled {
            get {
                return ((bool)(this["ACDCEnabled"]));
            }
            set {
                this["ACDCEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool RaidersRevengeEnabled {
            get {
                return ((bool)(this["RaidersRevengeEnabled"]));
            }
            set {
                this["RaidersRevengeEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MerryMintEnabled {
            get {
                return ((bool)(this["MerryMintEnabled"]));
            }
            set {
                this["MerryMintEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DualRaidersEnabled {
            get {
                return ((bool)(this["DualRaidersEnabled"]));
            }
            set {
                this["DualRaidersEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool StarWandEnabled {
            get {
                return ((bool)(this["StarWandEnabled"]));
            }
            set {
                this["StarWandEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ReaperEnabled {
            get {
                return ((bool)(this["ReaperEnabled"]));
            }
            set {
                this["ReaperEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool PartyAnimalEnabled {
            get {
                return ((bool)(this["PartyAnimalEnabled"]));
            }
            set {
                this["PartyAnimalEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:/")]
        public string musicPath {
            get {
                return ((string)(this["musicPath"]));
            }
            set {
                this["musicPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string musicName {
            get {
                return ((string)(this["musicName"]));
            }
            set {
                this["musicName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TakeTheLEnabled {
            get {
                return ((bool)(this["TakeTheLEnabled"]));
            }
            set {
                this["TakeTheLEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SlickEnabled {
            get {
                return ((bool)(this["SlickEnabled"]));
            }
            set {
                this["SlickEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ScenarioEnabled {
            get {
                return ((bool)(this["ScenarioEnabled"]));
            }
            set {
                this["ScenarioEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool PonyUpEnabled {
            get {
                return ((bool)(this["PonyUpEnabled"]));
            }
            set {
                this["PonyUpEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool PokiEnabled {
            get {
                return ((bool)(this["PokiEnabled"]));
            }
            set {
                this["PokiEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool NeverGonnaEnabled {
            get {
                return ((bool)(this["NeverGonnaEnabled"]));
            }
            set {
                this["NeverGonnaEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool LazerBlastEnabled {
            get {
                return ((bool)(this["LazerBlastEnabled"]));
            }
            set {
                this["LazerBlastEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool LlamacadabraEnabled {
            get {
                return ((bool)(this["LlamacadabraEnabled"]));
            }
            set {
                this["LlamacadabraEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool InfectiousEnabled {
            get {
                return ((bool)(this["InfectiousEnabled"]));
            }
            set {
                this["InfectiousEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool GlowsticksEnabled {
            get {
                return ((bool)(this["GlowsticksEnabled"]));
            }
            set {
                this["GlowsticksEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool LevitateEnabled {
            get {
                return ((bool)(this["LevitateEnabled"]));
            }
            set {
                this["LevitateEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool FlossEnabled {
            get {
                return ((bool)(this["FlossEnabled"]));
            }
            set {
                this["FlossEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool FlapperEnabled {
            get {
                return ((bool)(this["FlapperEnabled"]));
            }
            set {
                this["FlapperEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DaydreamEnabled {
            get {
                return ((bool)(this["DaydreamEnabled"]));
            }
            set {
                this["DaydreamEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DrakeEnabled {
            get {
                return ((bool)(this["DrakeEnabled"]));
            }
            set {
                this["DrakeEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool BlackShieldEnabled {
            get {
                return ((bool)(this["BlackShieldEnabled"]));
            }
            set {
                this["BlackShieldEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IllusionRuneEnabled {
            get {
                return ((bool)(this["IllusionRuneEnabled"]));
            }
            set {
                this["IllusionRuneEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool FlameSigilEnabled {
            get {
                return ((bool)(this["FlameSigilEnabled"]));
            }
            set {
                this["FlameSigilEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool GalacticDiscEnabled {
            get {
                return ((bool)(this["GalacticDiscEnabled"]));
            }
            set {
                this["GalacticDiscEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool FallenWingsEnabled {
            get {
                return ((bool)(this["FallenWingsEnabled"]));
            }
            set {
                this["FallenWingsEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DiscoBallEnabled {
            get {
                return ((bool)(this["DiscoBallEnabled"]));
            }
            set {
                this["DiscoBallEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool GalaxyWingsEnabled {
            get {
                return ((bool)(this["GalaxyWingsEnabled"]));
            }
            set {
                this["GalaxyWingsEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool FireVortexEnabled {
            get {
                return ((bool)(this["FireVortexEnabled"]));
            }
            set {
                this["FireVortexEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool GhostPortalEnabled {
            get {
                return ((bool)(this["GhostPortalEnabled"]));
            }
            set {
                this["GhostPortalEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool GlimmeringCloakEnabled {
            get {
                return ((bool)(this["GlimmeringCloakEnabled"]));
            }
            set {
                this["GlimmeringCloakEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool InsigniaEnabled {
            get {
                return ((bool)(this["InsigniaEnabled"]));
            }
            set {
                this["InsigniaEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool RainbowCloverEnabled {
            get {
                return ((bool)(this["RainbowCloverEnabled"]));
            }
            set {
                this["RainbowCloverEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool BackupPlanEnabled {
            get {
                return ((bool)(this["BackupPlanEnabled"]));
            }
            set {
                this["BackupPlanEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TheWormEnabled {
            get {
                return ((bool)(this["TheWormEnabled"]));
            }
            set {
                this["TheWormEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ToosieSlideEnabled {
            get {
                return ((bool)(this["ToosieSlideEnabled"]));
            }
            set {
                this["ToosieSlideEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool FishinEnabled {
            get {
                return ((bool)(this["FishinEnabled"]));
            }
            set {
                this["FishinEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SmoothMovesEnabled {
            get {
                return ((bool)(this["SmoothMovesEnabled"]));
            }
            set {
                this["SmoothMovesEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool FreestylinEnabled {
            get {
                return ((bool)(this["FreestylinEnabled"]));
            }
            set {
                this["FreestylinEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CheerUpEnabled {
            get {
                return ((bool)(this["CheerUpEnabled"]));
            }
            set {
                this["CheerUpEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool FreshEnabled {
            get {
                return ((bool)(this["FreshEnabled"]));
            }
            set {
                this["FreshEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool PopLockEnabled {
            get {
                return ((bool)(this["PopLockEnabled"]));
            }
            set {
                this["PopLockEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool OrangeJusticeEnabled {
            get {
                return ((bool)(this["OrangeJusticeEnabled"]));
            }
            set {
                this["OrangeJusticeEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TheRenegadeEnabled {
            get {
                return ((bool)(this["TheRenegadeEnabled"]));
            }
            set {
                this["TheRenegadeEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool BattleShroudEnabled {
            get {
                return ((bool)(this["BattleShroudEnabled"]));
            }
            set {
                this["BattleShroudEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CovenCapeEnabled {
            get {
                return ((bool)(this["CovenCapeEnabled"]));
            }
            set {
                this["CovenCapeEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CrestedCapeEnabled {
            get {
                return ((bool)(this["CrestedCapeEnabled"]));
            }
            set {
                this["CrestedCapeEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CuddleBowEnabled {
            get {
                return ((bool)(this["CuddleBowEnabled"]));
            }
            set {
                this["CuddleBowEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DismalEnabled {
            get {
                return ((bool)(this["DismalEnabled"]));
            }
            set {
                this["DismalEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool EnduringCapeEnabled {
            get {
                return ((bool)(this["EnduringCapeEnabled"]));
            }
            set {
                this["EnduringCapeEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool RoyaleShieldEnabled {
            get {
                return ((bool)(this["RoyaleShieldEnabled"]));
            }
            set {
                this["RoyaleShieldEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ScalyEnabled {
            get {
                return ((bool)(this["ScalyEnabled"]));
            }
            set {
                this["ScalyEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SixStringEnabled {
            get {
                return ((bool)(this["SixStringEnabled"]));
            }
            set {
                this["SixStringEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SpectralSpineEnabled {
            get {
                return ((bool)(this["SpectralSpineEnabled"]));
            }
            set {
                this["SpectralSpineEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool StitchesEnabled {
            get {
                return ((bool)(this["StitchesEnabled"]));
            }
            set {
                this["StitchesEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool VenturionCapeEnabled {
            get {
                return ((bool)(this["VenturionCapeEnabled"]));
            }
            set {
                this["VenturionCapeEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool WolfpackEnabled {
            get {
                return ((bool)(this["WolfpackEnabled"]));
            }
            set {
                this["WolfpackEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AutumnsMantleEnabled {
            get {
                return ((bool)(this["AutumnsMantleEnabled"]));
            }
            set {
                this["AutumnsMantleEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ScenarioMusicEnabled {
            get {
                return ((bool)(this["ScenarioMusicEnabled"]));
            }
            set {
                this["ScenarioMusicEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ToosieMusicEnabled {
            get {
                return ((bool)(this["ToosieMusicEnabled"]));
            }
            set {
                this["ToosieMusicEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SuperOGEnabled {
            get {
                return ((bool)(this["SuperOGEnabled"]));
            }
            set {
                this["SuperOGEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool GalaxyEnabled {
            get {
                return ((bool)(this["GalaxyEnabled"]));
            }
            set {
                this["GalaxyEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool OGDefaultEnabled {
            get {
                return ((bool)(this["OGDefaultEnabled"]));
            }
            set {
                this["OGDefaultEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool StellarAxeEnabled {
            get {
                return ((bool)(this["StellarAxeEnabled"]));
            }
            set {
                this["StellarAxeEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CandyAxeEnabled {
            get {
                return ((bool)(this["CandyAxeEnabled"]));
            }
            set {
                this["CandyAxeEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool StuddedAxeEnabled {
            get {
                return ((bool)(this["StuddedAxeEnabled"]));
            }
            set {
                this["StuddedAxeEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool PinkFlamingoEnabled {
            get {
                return ((bool)(this["PinkFlamingoEnabled"]));
            }
            set {
                this["PinkFlamingoEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CrowbarEnabled {
            get {
                return ((bool)(this["CrowbarEnabled"]));
            }
            set {
                this["CrowbarEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool HarleyHitterEnabled {
            get {
                return ((bool)(this["HarleyHitterEnabled"]));
            }
            set {
                this["HarleyHitterEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SpikyEnabled {
            get {
                return ((bool)(this["SpikyEnabled"]));
            }
            set {
                this["SpikyEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool WidowsBiteEnabled {
            get {
                return ((bool)(this["WidowsBiteEnabled"]));
            }
            set {
                this["WidowsBiteEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DriverEnabled {
            get {
                return ((bool)(this["DriverEnabled"]));
            }
            set {
                this["DriverEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AxeOfChampionsEnabled {
            get {
                return ((bool)(this["AxeOfChampionsEnabled"]));
            }
            set {
                this["AxeOfChampionsEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool VisionEnabled {
            get {
                return ((bool)(this["VisionEnabled"]));
            }
            set {
                this["VisionEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int invalidm {
            get {
                return ((int)(this["invalidm"]));
            }
            set {
                this["invalidm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int invalidf {
            get {
                return ((int)(this["invalidf"]));
            }
            set {
                this["invalidf"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool BhangraBoogieEnabled {
            get {
                return ((bool)(this["BhangraBoogieEnabled"]));
            }
            set {
                this["BhangraBoogieEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool BootstrapsEnabled {
            get {
                return ((bool)(this["BootstrapsEnabled"]));
            }
            set {
                this["BootstrapsEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TrustyNo2Enabled {
            get {
                return ((bool)(this["TrustyNo2Enabled"]));
            }
            set {
                this["TrustyNo2Enabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IceBreakerEnabled {
            get {
                return ((bool)(this["IceBreakerEnabled"]));
            }
            set {
                this["IceBreakerEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ScarletCommanderEnabled {
            get {
                return ((bool)(this["ScarletCommanderEnabled"]));
            }
            set {
                this["ScarletCommanderEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DreamGalaxyEnabled {
            get {
                return ((bool)(this["DreamGalaxyEnabled"]));
            }
            set {
                this["DreamGalaxyEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool WhiteoutEnabled {
            get {
                return ((bool)(this["WhiteoutEnabled"]));
            }
            set {
                this["WhiteoutEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool KyraEnabled {
            get {
                return ((bool)(this["KyraEnabled"]));
            }
            set {
                this["KyraEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool RenegadeRaiderEnabled {
            get {
                return ((bool)(this["RenegadeRaiderEnabled"]));
            }
            set {
                this["RenegadeRaiderEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool RenegadeRaiderCEnabled {
            get {
                return ((bool)(this["RenegadeRaiderCEnabled"]));
            }
            set {
                this["RenegadeRaiderCEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool HavocEnabled {
            get {
                return ((bool)(this["HavocEnabled"]));
            }
            set {
                this["HavocEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool VelocityEnabled {
            get {
                return ((bool)(this["VelocityEnabled"]));
            }
            set {
                this["VelocityEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SkullTrooperEnabled {
            get {
                return ((bool)(this["SkullTrooperEnabled"]));
            }
            set {
                this["SkullTrooperEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool FateEnabled {
            get {
                return ((bool)(this["FateEnabled"]));
            }
            set {
                this["FateEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool outwestEnabled {
            get {
                return ((bool)(this["outwestEnabled"]));
            }
            set {
                this["outwestEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool PlagueEnabled {
            get {
                return ((bool)(this["PlagueEnabled"]));
            }
            set {
                this["PlagueEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool BrilliantStrikerEnabled {
            get {
                return ((bool)(this["BrilliantStrikerEnabled"]));
            }
            set {
                this["BrilliantStrikerEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MavenEnabled {
            get {
                return ((bool)(this["MavenEnabled"]));
            }
            set {
                this["MavenEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TropicalZoeyEnabled {
            get {
                return ((bool)(this["TropicalZoeyEnabled"]));
            }
            set {
                this["TropicalZoeyEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool BuckleUpEnabled {
            get {
                return ((bool)(this["BuckleUpEnabled"]));
            }
            set {
                this["BuckleUpEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ButterflyKnifeEnabled {
            get {
                return ((bool)(this["ButterflyKnifeEnabled"]));
            }
            set {
                this["ButterflyKnifeEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool GingerGunnerEnabled {
            get {
                return ((bool)(this["GingerGunnerEnabled"]));
            }
            set {
                this["GingerGunnerEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool BeachBomberEnabled {
            get {
                return ((bool)(this["BeachBomberEnabled"]));
            }
            set {
                this["BeachBomberEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string bodypathAPI {
            get {
                return ((string)(this["bodypathAPI"]));
            }
            set {
                this["bodypathAPI"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string headpathAPI {
            get {
                return ((string)(this["headpathAPI"]));
            }
            set {
                this["headpathAPI"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string pickaxepathAPI {
            get {
                return ((string)(this["pickaxepathAPI"]));
            }
            set {
                this["pickaxepathAPI"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string pickaxesoundpathAPI {
            get {
                return ((string)(this["pickaxesoundpathAPI"]));
            }
            set {
                this["pickaxesoundpathAPI"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string backblingpathAPI {
            get {
                return ((string)(this["backblingpathAPI"]));
            }
            set {
                this["backblingpathAPI"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string emotespathAPI {
            get {
                return ((string)(this["emotespathAPI"]));
            }
            set {
                this["emotespathAPI"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string idpathAPI {
            get {
                return ((string)(this["idpathAPI"]));
            }
            set {
                this["idpathAPI"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string head13pathAPI {
            get {
                return ((string)(this["head13pathAPI"]));
            }
            set {
                this["head13pathAPI"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string body13pathAPI {
            get {
                return ((string)(this["body13pathAPI"]));
            }
            set {
                this["body13pathAPI"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int offsethead13 {
            get {
                return ((int)(this["offsethead13"]));
            }
            set {
                this["offsethead13"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int offsetbody13 {
            get {
                return ((int)(this["offsetbody13"]));
            }
            set {
                this["offsetbody13"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string cppackAPI {
            get {
                return ((string)(this["cppackAPI"]));
            }
            set {
                this["cppackAPI"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string cppackAPI2 {
            get {
                return ((string)(this["cppackAPI2"]));
            }
            set {
                this["cppackAPI2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ChaosAgentEnabled {
            get {
                return ((bool)(this["ChaosAgentEnabled"]));
            }
            set {
                this["ChaosAgentEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AstroJackEnabled {
            get {
                return ((bool)(this["AstroJackEnabled"]));
            }
            set {
                this["AstroJackEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DynamoEnabled {
            get {
                return ((bool)(this["DynamoEnabled"]));
            }
            set {
                this["DynamoEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool LoveWingsEnabled {
            get {
                return ((bool)(this["LoveWingsEnabled"]));
            }
            set {
                this["LoveWingsEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CloakedShadowEnabled {
            get {
                return ((bool)(this["CloakedShadowEnabled"]));
            }
            set {
                this["CloakedShadowEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SirenEnabled {
            get {
                return ((bool)(this["SirenEnabled"]));
            }
            set {
                this["SirenEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool JuicyEAC1Enabled {
            get {
                return ((bool)(this["JuicyEAC1Enabled"]));
            }
            set {
                this["JuicyEAC1Enabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool JuicyEAC2Enabled {
            get {
                return ((bool)(this["JuicyEAC2Enabled"]));
            }
            set {
                this["JuicyEAC2Enabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool NogOpsEnabled {
            get {
                return ((bool)(this["NogOpsEnabled"]));
            }
            set {
                this["NogOpsEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool PsychoBanditEnabled {
            get {
                return ((bool)(this["PsychoBanditEnabled"]));
            }
            set {
                this["PsychoBanditEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool BreakpointEnabled {
            get {
                return ((bool)(this["BreakpointEnabled"]));
            }
            set {
                this["BreakpointEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ReconSpecialistEnabled {
            get {
                return ((bool)(this["ReconSpecialistEnabled"]));
            }
            set {
                this["ReconSpecialistEnabled"] = value;
            }
        }
    }
}
